feat: Production Status
BristolSTA/uobtheatre-api pull request #226
Opened 2021-08-09 10:08 UTC by atoff

Implements a status field on the production model

2021-08-09 17:08 UTC, atoff commented
@JElgar  Can we implement the Enum node here?

2021-08-10 22:24 UTC, JElgar requested changes
Looks good but the testing seems a bit weedy. When we were on the call there were 3 cases you tested:
- Logged in as a user with some draft permissions
- Logged in as not admin
- Not logged in
I would say all these cases should be tested for us to be confident that `Production` `qs` is doing what we want.

I also notice you have changed a lot of `gql_client` to `gql_client_flexible`. I assume this is because tests started to fail with the new filtering and no user. I think a better solution that signing in the user for every production test is to set the default status of a `Production` in the `ProductionFactory` to `PUBLISHED` and then keep the user logged out

2021-08-10 22:24 UTC, JElgar commented on uobtheatre/productions/test/test_schema.py
> +def test_draft_productions_not_shown(gql_client_flexible):
```suggestion
def test_draft_productions_not_shown_to_basic_user(gql_client_flexible):
```

2021-08-11 16:48 UTC, JElgar approved these changes
LGTM. Thanks for sorting the gql_client nonsense

2021-08-11 16:48 UTC, JElgar commented on conftest.py
> +from uobtheatre.schema import schema as appSchema
```suggestion
from uobtheatre.schema import schema as app_schema
```

2021-08-11 16:48 UTC, merged