feat: Production Creating
BristolSTA/uobtheatre-api pull request #353
Opened 2021-11-09 23:19 UTC by atoff

2021-11-12 12:51 UTC, JElgar commented on uobtheatre/discounts/schema.py
> +class Mutation(AuthMutation, graphene.ObjectType):
```suggestion
class Mutation(graphene.ObjectType):
```

2021-11-12 13:00 UTC, JElgar commented on uobtheatre/productions/models.py
> +            ("approve_production", "Can edit production once live"),
Wrong description

2021-11-12 13:00 UTC, JElgar commented on uobtheatre/productions/schema.py
> +        return EditProductionObjects.user_has(
Consider existing production on update

2021-11-29 23:26 UTC, atoff reviewed
Here you go @JElgar

2021-11-29 23:26 UTC, atoff commented on TODO.md
> +- Fix pylint stuff on alex's branch
Remove this file

2021-11-29 23:26 UTC, atoff commented on uobtheatre/images/schema.py
> +    images = graphene.List(ImageNode)
We don't need this

2021-11-29 23:26 UTC, atoff commented on uobtheatre/images/views.py
> +        file_serializer.save()
Can we rename the image file name to something random here?

2021-12-15 09:48 UTC, JElgar commented on uobtheatre/productions/migrations/0013_alter_production_facebook_event.py
> +# Generated by Django 3.2.9 on 2021-12-11 13:49
I'm going to add this migration into the refund branch so can we shove this in there. We can probably also do some squashing

2021-12-15 09:53 UTC, JElgar commented on uobtheatre/productions/migrations/0013_alter_production_facebook_event.py
> +# Generated by Django 3.2.9 on 2021-12-11 13:49
I also can't find the migration for post_Image but it seems thats changed as welll. I think the best plan is to: 
- delete all migrations in this branch
- merge with dev 
- regenerate migrations

2022-01-01 21:00 UTC, JElgar requested changes

2022-01-01 21:02 UTC, JElgar commented on uobtheatre/discounts/schema.py
> +                raise AuthorizationException
```suggestion
                raise AuthorizationException("You do not have the ability to edit one of the provided performances")
```

2022-01-01 21:46 UTC, JElgar commented on uobtheatre/discounts/schema.py
> +        return True
```suggestion
        return
```

2022-01-01 21:46 UTC, JElgar commented on uobtheatre/discounts/schema.py
> +                raise AuthorizationException()
```suggestion
                raise AuthorizationException("You do not have the ability to edit one of the provided performances")
```

2022-01-01 21:46 UTC, JElgar commented on uobtheatre/productions/abilities.py
> +    """Whether the user is able to change a production's details and sub-objects"""
Not quite

2022-01-01 21:46 UTC, JElgar commented on uobtheatre/productions/mutations.py
> +        return has_perm_new_performance and has_perm_current_performance
Same again

2022-01-01 21:46 UTC, JElgar commented on uobtheatre/productions/schema.py
> +
Do we need this?

2022-01-01 21:46 UTC, JElgar commented on uobtheatre/productions/schema.py
> +            qs = Production.objects.user_can_see(info.context.user)
Im cleaning this up a bit

2022-01-01 21:59 UTC, JElgar commented on uobtheatre/productions/test/test_flow.py
> +# pylint: disable=R0914,too-many-statements
Can we rename this to test_system

2022-01-01 22:11 UTC, JElgar commented on uobtheatre/utils/models.py
> +            )
What is going on here?

2022-01-01 22:14 UTC, JElgar commented on uobtheatre/utils/permissions.py
> +        only_with_perms_in="productions.approve_production",
Umm?

2022-01-01 22:16 UTC, JElgar commented on uobtheatre/utils/permissions.py
> +        content_type=ContentType.objects.get_for_model(Production),
?

2022-01-01 22:20 UTC, JElgar commented on uobtheatre/utils/schema.py
> +        if not isinstance(self, PermissionableModel):  # pragma: no cover
Can we test this?

2022-01-01 22:22 UTC, JElgar commented on uobtheatre/utils/schema.py
> +    # pylint: disable=C0116,arguments-differ
```suggestion
    # pylint: disable=arguments-differ
```

Lets add `__init_subclass_with_meta__` to the "no-docstring-rgx" in pylintrc

2022-01-01 22:24 UTC, JElgar commented on uobtheatre/utils/schema.py
> +        if "id" in input_items:
Can we move this comment and make it clear everything below is straight from graphene

2022-01-01 22:25 UTC, JElgar commented on uobtheatre/utils/schema.py
> +    # pylint: disable=W0212
```suggestion
    # pylint: disable=protected-access
```

2022-01-01 22:26 UTC, JElgar commented on uobtheatre/utils/schema.py
> +                raise AuthorizationException
Can we add a message here?

2022-01-01 22:26 UTC, JElgar commented on uobtheatre/utils/schema.py
> +            raise AuthorizationException
and here

2022-01-01 22:27 UTC, JElgar commented on uobtheatre/utils/schema.py
> +        if len(response.errors):
```suggestion
        if response.errors:
```

2022-01-01 22:29 UTC, JElgar commented on uobtheatre/utils/schema.py
> +            )
Can we move this to a custom exception? I've done a similar thing for SquareException which takes a square exception and then does the resolve in the resolve method. 
Something like FormException would be nice

2022-01-01 22:30 UTC, JElgar commented on uobtheatre/utils/schema.py
> +                raise AuthorizationException
Can we add a message

2022-01-01 22:30 UTC, JElgar commented on uobtheatre/utils/schema.py
> +            raise AuthorizationException
same here

2022-01-01 22:33 UTC, JElgar commented on uobtheatre/utils/schema.py
> +            raise AuthorizationException()
message

2022-01-01 22:33 UTC, JElgar commented on uobtheatre/utils/schema.py
> +                "A user with that email does not exist on our system",
```suggestion
                "A user with that email does not exist",
```

2022-01-01 23:48 UTC, JElgar approved these changes
LGMT

2022-01-01 23:48 UTC, merged